spring:

  application:
    name: PotjeraWebScraper

  datasource:
    url: jdbc:postgresql://localhost:5432/potjera
    username: potjera
    password: potjera
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false